Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
      vb.name = "manager01"
    end
  end

  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.network "private_network", ip: "192.168.33.11"
    node.vm.network "forwarded_port", guest: 81, host:8081 #session-service
    node.vm.network "forwarded_port", guest: 87, host:8087 #gateway-service
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
      vb.name = "node01"
    end
  end

  config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.network "private_network", ip: "192.168.33.12"
    node.vm.network "forwarded_port", guest: 80, host:8080 #Apache
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
      vb.name = "node02"
    end
  end
end 

